services:
  # web:
  #   build: .
  #   container_name: django_app
  #   command: python manage.py runserver 0.0.0.0:8000
  #   env_file: .env
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  #     DB_NAME: ${DB_NAME}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DATABASE_HOST: ${DATABASE_HOST}
  #     DATABASE_PORT: ${DATABASE_PORT}

  db:
    image: mongo:4.4
    container_name: mongo_db
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
