services:
  web:
    build: .
    container_name: django_app
    env_file: .env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db

  db:
    image: mongo:4.4
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
